### ISSUE TITLE
Proposal for new Git workflow.

### ISSUE THREAD

**Issue by jscervantes** [lyzidiamond/i-have-subwayed#6]
_Hi Team!_

I don't think we've had a chance to talk about what kind of Git workflow we should follow as we develop i-have-subwayed, so this is my attempt at that. 

I think Scott Chacon lays out a great blueprint in _Pro Git_ pgs 82-85 (will send pdf out). Specifically, we will keep two branches in play at all times:

* __Main__: This will be our stable branch.
* __Dev__: This will be the branch that we merge new _topic/feature_ branches into. We will _merge_ it into main once we know everything is in working order.

_Topic/feature_ branches will be made for any new thing we want to add to our project. There will be many of these--the more the merrier. Will make it easier to look over our commit history and identify what/when things were added.

Anyways, as always, want to hear your thoughts!

- Jose

**Comment by lyzidiamond** [comment]
yes good
